### ISSUE TITLE
empty splitters

### ISSUE THREAD

**Issue by xtYao** [hall-lab/extract_sv_reads#10]
Hi -

Trying to call somatic SV from tumor/normal pair WGS BAMs aligned by `bwa aln`, but get empty splitters but populated discordants.

I was directed by @cc2qe from the speedseq issue (https://github.com/hall-lab/speedseq/issues/22#issuecomment-413702767) to this new pipeline. Yet, just like the other two ways I've tried, 1) using `speedseq sv` without giving path to splitters and let it resolve in its default way, and 2) deliberately call `speedseq realign` to obtain the splitters and discordants. Neither worked.

My BAM header looks like:
[bam.header.txt](https://github.com/hall-lab/extract_sv_reads/files/2318600/bam.header.txt)

The command I used is:
```
extract-sv-reads --threads 6 --min-non-overlap 5 -s new.splitter.bam -i sample.bam -d new.discordant.bam
```

Please kindly let me know the best/fastest way to prepare the splitters so that speedseq/lumpy can use for SV calling. Thanks!

Xiaotong

**Comment by ernfrid** [comment]
`bwa aln` doesn't produce split read alignments. While Colby is correct that you can use this tool to extract splitters and discordants from a `bwa mem` aligned BAM or CRAM that wasn't aligned via `speedseq`, it relies on the `SA` tags produced by `bwa mem` and won't work on alignments from `bwa aln`.

An imperfect workaround might be to:
1) Extract all unmapped reads and any aligned mates from your source BAM to produce a file of all paired reads where both or one side is unaligned.
2) Realign just these reads using `bwa mem` directly or `speedseq realign`
3) Merge/combine the discordants BAM from your original alignments with discordants from the `bwa mem` alignments.
4) Proceed with SV detection using your combined discordants BAM and you splitters file from `bwa mem`.

This seems pretty complicated to me and has some obvious caveats in that there may be mismapped reads in your original file that you'd miss out on. I can imagine selecting read pairs with high numbers of mismatches for realignment as well.

You may also want to inquire about `bwa aln` aligned BAMs on the lumpy Google group or github page to see if there are better work arounds than what I suggest above.

**Comment by xtYao** [comment]
Dave,

You're right. The only way that produced splitters is by running `speedseq realign` on the input BAM. (I was wrong in the original post.) I guess for these BAM we'll just pay the due time and wait for the realignment then.

Thanks,
Xiaotong

**Comment by ernfrid** [comment]
You're welcome. Good luck!
