### ISSUE TITLE
extract-sv-reads build fails

### ISSUE THREAD

**Issue by jbsysadmin** [hall-lab/extract_sv_reads#9]
Greetings.

I just attempted a build of version 1.2.1, extract-sv-reads. This is Centos 6.9, with binutils-2.26.1, gcc-4.9.3, & cmake-3.5.2 in PATH.
The resulting build fails in an error that ends as below.

Any leads?

-John

--- excerpt ---
[ 97%] Linking CXX executable ../../../../bin/extract-sv-reads
../../../../vendor/boost/lib/libboost_program_options.a(cmdline.o): In function `boost::program_options::detail::cmdline::parse_long_option(std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)':
cmdline.cpp:(.text+0x1c8a): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
cmdline.cpp:(.text+0x1cb4): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
cmdline.cpp:(.text+0x1cdf): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
../../../../vendor/boost/lib/libboost_program_options.a(cmdline.o): In function `boost::program_options::detail::cmdline::parse_dos_option(std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)':
cmdline.cpp:(.text+0x2426): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
../../../../vendor/boost/lib/libboost_program_options.a(cmdline.o): In function `boost::program_options::detail::cmdline::parse_short_option(std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)':
cmdline.cpp:(.text+0x2fb6): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
../../../../vendor/boost/lib/libboost_program_options.a(cmdline.o):cmdline.cpp:(.text+0x548d): more undefined references to `std::__throw_out_of_range_fmt(char const*, ...)' follow
collect2: ld returned 1 exit status
make[2]: *** [bin/extract-sv-reads] Error 1
make[1]: *** [build/src/exe/extract_sv_reads/CMakeFiles/extract-sv-reads.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX executable ../../../../test-bin/TestExtractSvReadsLib
../../../../vendor/gtest160-build/libgtest.a(gtest-all.cc.o): In function `std::vector<testing::TestPartResult, std::allocator<testing::TestPartResult> >::_M_range_check(unsigned long) const':
gtest-all.cc:(.text._ZNKSt6vectorIN7testing14TestPartResultESaIS1_EE14_M_range_checkEm[std::vector<testing::TestPartResult, std::allocator<testing::TestPartResult> >::_M_range_check(unsigned long) const]+0x48): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
../../../../vendor/gtest160-build/libgtest.a(gtest-all.cc.o): In function `std::vector<testing::TestProperty, std::allocator<testing::TestProperty> >::_M_range_check(unsigned long) const':
gtest-all.cc:(.text._ZNKSt6vectorIN7testing12TestPropertyESaIS1_EE14_M_range_checkEm[std::vector<testing::TestProperty, std::allocator<testing::TestProperty> >::_M_range_check(unsigned long) const]+0x48): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
collect2: ld returned 1 exit status
make[2]: *** [test-bin/TestExtractSvReadsLib] Error 1
make[1]: *** [build/test/lib/process_splitters/CMakeFiles/TestExtractSvReadsLib.dir/all] Error 2
make: *** [all] Error 2

**Comment by ernfrid** [comment]
By any chance do you have multiple versions of gcc and thus libstdc++ compiled on this machine?

**Comment by jbsysadmin** [comment]
Thanks for response.
The gcc is a custom build, sitting on an NFS share and added to PATH / LB_LIBRARY_PATH.
Users sometimes want certain items later than those in the host OS. We build the related libraries and compilers. GCC 4.4.7 comes with the OS; I used 4.9.3.

**Comment by ernfrid** [comment]
Based on some cursory Google hits, it seems like a possibility that this is due to mismatching libstdc++ versions. It's not clear to me how variables like LD_LIBRARY_PATH are handled during the cmake build process so I wonder if it's not appropriately set.

This will need more research on my end to come up with a work around and I'm not sure when I might get to that.

A few quick questions:
Are the changes to PATH/LD_LIBRARY_PATH exported? 
Or are they being set alongside the call to cmake and make (e.g. LD_LIBRARY_PATH=/some/location:$LD_LIBRARY_PATH cmake ..`)?

**Comment by jbsysadmin** [comment]
As it happens, I got further using the in-OS gcc and cmake.

This time, “make –j” finished without incident. In make test, I include the conclusion of the output.
Is there a libxml dependency to consider?

libxml2.so.2: no version information available (required by /usr/lib64/libarchive.so.2)
Test project /usr/local/installs/extract_sv_reads-1.2.1/build
    Start 1: TestExtractSvReadsLib
1/2 Test #1: TestExtractSvReadsLib ............   Passed    0.00 sec
    Start 2: TestExtractSvReads
2/2 Test #2: TestExtractSvReads ...............***Failed    0.15 sec

50% tests passed, 1 tests failed out of 2

Label Time Summary:
integration    =   0.15 sec
unit           =   0.00 sec

Total Test time (real) =   0.15 sec

The following tests FAILED:
          2 - TestExtractSvReads (Failed)
Errors while running CTest
make: *** [test] Error 8

**Comment by ernfrid** [comment]
Looking at a few other binaries I have compiled below, I don't see libxml or libarchive referenced. However, it does look like the integration test depends on lxml being installed and lxml requires libxml (https://lxml.de/installation.html). My best guess is that this is the root issue causing the error.


```

$ otool -L extract-sv-reads
extract-sv-reads:
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
/usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 9.0.0)
/usr/lib/libcrypto.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
/usr/lib/libssl.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
/usr/lib/liblzma.5.dylib (compatibility version 6.0.0, current version 6.3.0)
/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)


$ ldd ~/bin/extract-sv-reads.tmp
linux-vdso.so.1 =>  (0x00007ffce4259000)
libpthread.so.0 => /lib/libpthread.so.0 (0x00007effd4915000)
librt.so.1 => /lib/librt.so.1 (0x00007effd470c000)
libz.so.1 => /gscmnt/gc2802/halllab/idas/software/zlib-1.2.11/lib/libz.so.1 (0x00007effd44f3000)
libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007effd41df000)
libm.so.6 => /lib/libm.so.6 (0x00007effd3f5b000)
libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x00007effd3d44000)
libc.so.6 => /lib/libc.so.6 (0x00007effd39bb000)
/lib64/ld-linux-x86-64.so.2 (0x0000557ed0f97000)
```


________________________________

**Comment by jbsysadmin** [comment]
I tried a build under Centos 7, and there were no errors or concerns at all.
As there is an RHEL7-era migration pending, it may be better just to wait until the install base changes to 7.x.

Thank you for your time, please close.

[edit]
________________________________

**Comment by ernfrid** [comment]
Will do. Glad you were able to get it working.
